/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-08-20 11:38:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"border-bottom \">\r\n");
      out.write("    <div class=\"bg-light py-1\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-12 text-center text-md-start\"><span> Super Value Deals - Save more with\r\n");
      out.write("              coupons</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-6 text-end d-none d-md-block\">\r\n");
      out.write("                    <div class=\"dropdown selectBox\">\r\n");
      out.write("                        <a class=\"dropdown-toggle selectValue text-reset\" href=\"javascript:void(0)\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                <span class=\"me-1\">\r\n");
      out.write("                  <svg width=\"16\" height=\"13\" viewBox=\"0 0 16 13\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <g clip-path=\"url(#selectedlang)\">\r\n");
      out.write("                      <path d=\"M0 0.5H16V12.5H0V0.5Z\" fill=\"#012169\" />\r\n");
      out.write("                      <path\r\n");
      out.write("                              d=\"M1.875 0.5L7.975 5.025L14.05 0.5H16V2.05L10 6.525L16 10.975V12.5H14L8 8.025L2.025 12.5H0V11L5.975 6.55L0 2.1V0.5H1.875Z\"\r\n");
      out.write("                              fill=\"white\" />\r\n");
      out.write("                      <path\r\n");
      out.write("                              d=\"M10.6 7.525L16 11.5V12.5L9.225 7.525H10.6ZM6 8.025L6.15 8.9L1.35 12.5H0L6 8.025ZM16 0.5V0.575L9.775 5.275L9.825 4.175L14.75 0.5H16ZM0 0.5L5.975 4.9H4.475L0 1.55V0.5Z\"\r\n");
      out.write("                              fill=\"#C8102E\" />\r\n");
      out.write("                      <path d=\"M6.025 0.5V12.5H10.025V0.5H6.025ZM0 4.5V8.5H16V4.5H0Z\" fill=\"white\" />\r\n");
      out.write("                      <path d=\"M0 5.325V7.725H16V5.325H0ZM6.825 0.5V12.5H9.225V0.5H6.825Z\" fill=\"#C8102E\" />\r\n");
      out.write("                    </g>\r\n");
      out.write("                    <defs>\r\n");
      out.write("                      <clipPath id=\"selectedlang\">\r\n");
      out.write("                        <rect width=\"16\" height=\"12\" fill=\"white\" transform=\"translate(0 0.5)\" />\r\n");
      out.write("                      </clipPath>\r\n");
      out.write("                    </defs>\r\n");
      out.write("                  </svg>\r\n");
      out.write("                </span>English\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"javascript:void(0)\"> <span class=\"me-1\">\r\n");
      out.write("                  <svg width=\"16\" height=\"13\" viewBox=\"0 0 16 13\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <g clip-path=\"url(#selectedlang)\">\r\n");
      out.write("                      <path d=\"M0 0.5H16V12.5H0V0.5Z\" fill=\"#012169\" />\r\n");
      out.write("                      <path\r\n");
      out.write("                              d=\"M1.875 0.5L7.975 5.025L14.05 0.5H16V2.05L10 6.525L16 10.975V12.5H14L8 8.025L2.025 12.5H0V11L5.975 6.55L0 2.1V0.5H1.875Z\"\r\n");
      out.write("                              fill=\"white\" />\r\n");
      out.write("                      <path\r\n");
      out.write("                              d=\"M10.6 7.525L16 11.5V12.5L9.225 7.525H10.6ZM6 8.025L6.15 8.9L1.35 12.5H0L6 8.025ZM16 0.5V0.575L9.775 5.275L9.825 4.175L14.75 0.5H16ZM0 0.5L5.975 4.9H4.475L0 1.55V0.5Z\"\r\n");
      out.write("                              fill=\"#C8102E\" />\r\n");
      out.write("                      <path d=\"M6.025 0.5V12.5H10.025V0.5H6.025ZM0 4.5V8.5H16V4.5H0Z\" fill=\"white\" />\r\n");
      out.write("                      <path d=\"M0 5.325V7.725H16V5.325H0ZM6.825 0.5V12.5H9.225V0.5H6.825Z\" fill=\"#C8102E\" />\r\n");
      out.write("                    </g>\r\n");
      out.write("                    <defs>\r\n");
      out.write("                      <clipPath id=\"selectedlang\">\r\n");
      out.write("                        <rect width=\"16\" height=\"12\" fill=\"white\" transform=\"translate(0 0.5)\" />\r\n");
      out.write("                      </clipPath>\r\n");
      out.write("                    </defs>\r\n");
      out.write("                  </svg>\r\n");
      out.write("                </span>English</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"javascript:void(0)\"><span class=\"me-2\">\r\n");
      out.write("\r\n");
      out.write("                  <svg width=\"16\" height=\"13\" viewBox=\"0 0 16 13\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                    <g clip-path=\"url(#clip0_5543_19751)\">\r\n");
      out.write("                      <path d=\"M0 8.5H16V12.5H0V8.5Z\" fill=\"#FFCE00\" />\r\n");
      out.write("                      <path d=\"M0 0.5H16V4.5H0V0.5Z\" fill=\"black\" />\r\n");
      out.write("                      <path d=\"M0 4.5H16V8.5H0V4.5Z\" fill=\"#DD0000\" />\r\n");
      out.write("                    </g>\r\n");
      out.write("                    <defs>\r\n");
      out.write("                      <clipPath id=\"clip0_5543_19751\">\r\n");
      out.write("                        <rect width=\"16\" height=\"12\" fill=\"white\" transform=\"translate(0 0.5)\" />\r\n");
      out.write("                      </clipPath>\r\n");
      out.write("                    </defs>\r\n");
      out.write("                  </svg>\r\n");
      out.write("\r\n");
      out.write("                </span>Deutsch</a></li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row w-100 align-items-center gx-lg-2 gx-0\">\r\n");
      out.write("                <div class=\"col-xxl-2 col-lg-3\">\r\n");
      out.write("                    <a class=\"navbar-brand d-none d-lg-block\" href=\"index.html\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/logo/freshcart-logo.svg\" alt=\"eCommerce HTML Template\">\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"d-flex justify-content-between w-100 d-lg-none\">\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/logo/freshcart-logo.svg\" alt=\"eCommerce HTML Template\">\r\n");
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-flex align-items-center lh-1\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"list-inline me-4\">\r\n");
      out.write("                                <div class=\"list-inline-item\">\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"#!\" class=\"text-muted\" data-bs-toggle=\"modal\" data-bs-target=\"#userModal\">\r\n");
      out.write("                                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                             stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                             class=\"feather feather-user\">\r\n");
      out.write("                                            <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("                                            <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"list-inline-item\">\r\n");
      out.write("\r\n");
      out.write("                                    <a class=\"text-muted position-relative \" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasRight\"\r\n");
      out.write("                                       href=\"#offcanvasExample\" role=\"button\" aria-controls=\"offcanvasRight\">\r\n");
      out.write("                                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                             stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                             class=\"feather feather-shopping-bag\">\r\n");
      out.write("                                            <path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\"></path>\r\n");
      out.write("                                            <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line>\r\n");
      out.write("                                            <path d=\"M16 10a4 4 0 0 1-8 0\"></path>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                        <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-success\">\r\n");
      out.write("                        1\r\n");
      out.write("                        <span class=\"visually-hidden\">unread messages</span>\r\n");
      out.write("                      </span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Button -->\r\n");
      out.write("                            <button class=\"navbar-toggler collapsed\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#navbar-default\" aria-controls=\"navbar-default\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" fill=\"currentColor\"\r\n");
      out.write("                                     class=\"bi bi-text-indent-left text-primary\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path\r\n");
      out.write("                                            d=\"M2 3.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5zm.646 2.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L4.293 8 2.646 6.354a.5.5 0 0 1 0-.708zM7 6.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 3a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm-5 3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xxl-5 col-lg-5 d-none d-lg-block\">\r\n");
      out.write("\r\n");
      out.write("                    <form action=\"#\">\r\n");
      out.write("                        <div class=\"input-group \">\r\n");
      out.write("                            <input class=\"form-control rounded\" type=\"search\" placeholder=\"Search for products\">\r\n");
      out.write("                            <span class=\"input-group-append\">\r\n");
      out.write("                  <button class=\"btn bg-white border border-start-0 ms-n10 rounded-0 rounded-end\" type=\"button\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                         stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                         class=\"feather feather-search\">\r\n");
      out.write("                      <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\r\n");
      out.write("                      <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                  </button>\r\n");
      out.write("                </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-xxl-3 d-none d-lg-block\">\r\n");
      out.write("                    <!-- Button trigger modal -->\r\n");
      out.write("                    <button type=\"button\" class=\"btn  btn-outline-gray-400 text-muted\" data-bs-toggle=\"modal\"\r\n");
      out.write("                            data-bs-target=\"#locationModal\">\r\n");
      out.write("                        <i class=\"feather-icon icon-map-pin me-2\"></i>Location\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 col-xxl-2 text-end d-none d-lg-block\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"list-inline\">\r\n");
      out.write("                        <div class=\"list-inline-item me-5\">\r\n");
      out.write("\r\n");
      out.write("                            <a href=\"pages/shop-wishlist.html\" class=\"text-muted position-relative\">\r\n");
      out.write("\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                     stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                     class=\"feather feather-heart\">\r\n");
      out.write("                                    <path\r\n");
      out.write("                                            d=\"M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z\">\r\n");
      out.write("                                    </path>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-success\">\r\n");
      out.write("                    5\r\n");
      out.write("                    <span class=\"visually-hidden\">unread messages</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                            </a></div>\r\n");
      out.write("                        <div class=\"list-inline-item me-5\">\r\n");
      out.write("\r\n");
      out.write("                            <a href=\"#!\" class=\"text-muted\" data-bs-toggle=\"modal\" data-bs-target=\"#userModal\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                     stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                     class=\"feather feather-user\">\r\n");
      out.write("                                    <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\r\n");
      out.write("                                    <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </a></div>\r\n");
      out.write("                        <div class=\"list-inline-item\">\r\n");
      out.write("\r\n");
      out.write("                            <a class=\"text-muted position-relative \" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasRight\"\r\n");
      out.write("                               href=\"#offcanvasExample\" role=\"button\" aria-controls=\"offcanvasRight\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                     stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                     class=\"feather feather-shopping-bag\">\r\n");
      out.write("                                    <path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\"></path>\r\n");
      out.write("                                    <line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line>\r\n");
      out.write("                                    <path d=\"M16 10a4 4 0 0 1-8 0\"></path>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-success\">\r\n");
      out.write("                    1\r\n");
      out.write("                    <span class=\"visually-hidden\">unread messages</span>\r\n");
      out.write("                  </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light navbar-default py-0 pb-lg-4 \" aria-label=\"Offcanvas navbar large\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\" id=\"navbar-default\" aria-labelledby=\"navbar-defaultLabel\">\r\n");
      out.write("                <div class=\"offcanvas-header pb-1\">\r\n");
      out.write("                    <a href=\"index.html\"><img src=\"assets/images/logo/freshcart-logo.svg\" alt=\"eCommerce HTML Template\"></a>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"offcanvas-body\">\r\n");
      out.write("                    <div class=\"d-block d-lg-none mb-4\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"input-group \">\r\n");
      out.write("                                <input class=\"form-control rounded\" type=\"search\" placeholder=\"Search for products\">\r\n");
      out.write("                                <span class=\"input-group-append\">\r\n");
      out.write("                    <button class=\"btn bg-white border border-start-0 ms-n10 rounded-0 rounded-end\" type=\"button\">\r\n");
      out.write("                      <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                           stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                           class=\"feather feather-search\">\r\n");
      out.write("                        <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\r\n");
      out.write("                        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\r\n");
      out.write("                      </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"mt-2\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn  btn-outline-gray-400 text-muted w-100 \" data-bs-toggle=\"modal\"\r\n");
      out.write("                                    data-bs-target=\"#locationModal\">\r\n");
      out.write("                                <i class=\"feather-icon icon-map-pin me-2\"></i>Pick Location\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-block d-lg-none mb-4\">\r\n");
      out.write("                        <a class=\"btn btn-primary w-100 d-flex justify-content-center align-items-center\" data-bs-toggle=\"collapse\"\r\n");
      out.write("                           href=\"#collapseExample\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseExample\">\r\n");
      out.write("                <span class=\"me-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                        fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                        class=\"feather feather-grid\">\r\n");
      out.write("                    <rect x=\"3\" y=\"3\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"14\" y=\"3\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"14\" y=\"14\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"3\" y=\"14\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                  </svg></span> All Departments\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"collapse mt-2\" id=\"collapseExample\">\r\n");
      out.write("                            <div class=\"card card-body\">\r\n");
      out.write("                                <ul class=\"mb-0 list-unstyled\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Dairy, Bread & Eggs</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Snacks & Munchies</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Fruits & Vegetables</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Cold Drinks & Juices</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Breakfast & Instant Food</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Bakery & Biscuits</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Chicken, Meat & Fish</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dropdown me-3 d-none d-lg-block\">\r\n");
      out.write("                        <button class=\"btn btn-primary px-6 \" type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                <span class=\"me-1\">\r\n");
      out.write("                  <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                       stroke=\"currentColor\" stroke-width=\"1.2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                       class=\"feather feather-grid\">\r\n");
      out.write("                    <rect x=\"3\" y=\"3\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"14\" y=\"3\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"14\" y=\"14\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                    <rect x=\"3\" y=\"14\" width=\"7\" height=\"7\"></rect>\r\n");
      out.write("                  </svg></span> All Departments\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Dairy, Bread & Eggs</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Snacks & Munchies</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Fruits & Vegetables</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Cold Drinks & Juices</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Breakfast & Instant Food</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Bakery & Biscuits</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Chicken, Meat & Fish</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"\">\r\n");
      out.write("                        <ul class=\"navbar-nav align-items-center \">\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Home\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"index.html\">Home 1</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/index-2.html\">Home 2</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/index-3.html\">Home 3</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/index-4.html\">Home 4</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/index-5.html\">Home 5 <span\r\n");
      out.write("                                            class=\"badge bg-light-info text-dark-info ms-1\">New</span></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Shop\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Shop Grid - Filter</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-grid-3-column.html\">Shop Grid - 3 column</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-list.html\">Shop List - Filter</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-filter.html\">Shop - Filter</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-fullwidth.html\">Shop Wide</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-single.html\">Shop Single</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-single-2.html\">Shop Single v2</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-wishlist.html\">Shop Wishlist</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-cart.html\">Shop Cart</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/shop-checkout.html\">Shop Checkout</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Stores\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/store-list.html\">Store List</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/store-grid.html\">Store Grid</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/store-single.html\">Store Single</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto dropdown-fullwidth\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Mega menu\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\" dropdown-menu pb-0\">\r\n");
      out.write("                                    <div class=\"row p-2 p-lg-4\">\r\n");
      out.write("                                        <div class=\"col-lg-3 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("                                            <h6 class=\"text-primary ps-3\">Dairy, Bread & Eggs</h6>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Butter</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Milk Drinks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Curd & Yogurt</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Eggs</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Buns & Bakery</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Cheese</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Condensed Milk</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Dairy Products</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-lg-3 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("                                            <h6 class=\"text-primary ps-3\">Breakfast & Instant Food</h6>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Breakfast Cereal</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Noodles, Pasta & Soup</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Frozen Veg Snacks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Frozen Non-Veg Snacks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Vermicelli</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Instant Mixes</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Batter</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\"> Fruit and Juices</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-lg-3 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("                                            <h6 class=\"text-primary ps-3\">Cold Drinks & Juices</h6>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Soft Drinks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Fruit Juices</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Coldpress</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Water & Ice Cubes</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Soda & Mixers</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Health Drinks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Herbal Drinks</a>\r\n");
      out.write("                                            <a class=\"dropdown-item\" href=\"pages/shop-grid.html\">Milk Drinks</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-lg-3 col-12 mb-4 mb-lg-0\">\r\n");
      out.write("                                            <div class=\"card border-0\">\r\n");
      out.write("                                                <img src=\"assets/images/banner/menu-banner.jpg\" alt=\"eCommerce HTML Template\"\r\n");
      out.write("                                                     class=\"img-fluid\">\r\n");
      out.write("                                                <div class=\"position-absolute ps-6 mt-8\">\r\n");
      out.write("                                                    <h5 class=\" mb-0 \">Dont miss this <br>offer today.</h5>\r\n");
      out.write("                                                    <a href=\"#\" class=\"btn btn-primary btn-sm mt-3\">Shop Now</a>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Pages\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/blog.html\">Blog</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/blog-single.html\">Blog Single</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/blog-category.html\">Blog Category</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/about.html\">About us</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/404error.html\">404 Error</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/contact.html\">Contact</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-expanded=\"false\">\r\n");
      out.write("                                    Account\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/signin.html\">Sign in</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/signup.html\">Signup</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"pages/forgot-password.html\">Forgot Password</a></li>\r\n");
      out.write("                                    <li class=\"dropdown-submenu dropend\">\r\n");
      out.write("                                        <a class=\"dropdown-item dropdown-list-group-item dropdown-toggle\" href=\"#\">\r\n");
      out.write("                                            My Account\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                                            <li><a class=\"dropdown-item\" href=\"pages/account-orders.html\">Orders</a></li>\r\n");
      out.write("                                            <li><a class=\"dropdown-item\" href=\"pages/account-settings.html\">Settings</a></li>\r\n");
      out.write("                                            <li><a class=\"dropdown-item\" href=\"pages/account-address.html\">Address</a></li>\r\n");
      out.write("                                            <li><a class=\"dropdown-item\" href=\"pages/account-payment-method.html\">Payment Method</a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a class=\"dropdown-item\" href=\"pages/account-notification.html\">Notification</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item w-100 w-lg-auto\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"dashboard/index.html\">\r\n");
      out.write("                                    Dashboard\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item dropdown w-100 w-lg-auto dropdown-flyout\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\" id=\"navbarDropdownDocs\" role=\"button\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                   aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                    Docs\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"dropdown-menu dropdown-menu-lg\" aria-labelledby=\"navbarDropdownDocs\">\r\n");
      out.write("                                    <a class=\"dropdown-item align-items-start\" href=\"docs/index.html\">\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\"\r\n");
      out.write("                                                 class=\"bi bi-file-text text-primary\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                <path\r\n");
      out.write("                                                        d=\"M5 4a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm-.5 2.5A.5.5 0 0 1 5 6h6a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5zM5 8a.5.5 0 0 0 0 1h6a.5.5 0 0 0 0-1H5zm0 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1H5z\" />\r\n");
      out.write("                                                <path\r\n");
      out.write("                                                        d=\"M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z\" />\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"ms-3 lh-1\">\r\n");
      out.write("                                            <h6 class=\"mb-1\">Documentations</h6>\r\n");
      out.write("                                            <p class=\"mb-0 small\">\r\n");
      out.write("                                                Browse the all documentation\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <a class=\"dropdown-item align-items-start\" href=\"docs/changelog.html\">\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" fill=\"currentColor\"\r\n");
      out.write("                                                 class=\"bi bi-layers text-primary\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                                <path\r\n");
      out.write("                                                        d=\"M8.235 1.559a.5.5 0 0 0-.47 0l-7.5 4a.5.5 0 0 0 0 .882L3.188 8 .264 9.559a.5.5 0 0 0 0 .882l7.5 4a.5.5 0 0 0 .47 0l7.5-4a.5.5 0 0 0 0-.882L12.813 8l2.922-1.559a.5.5 0 0 0 0-.882l-7.5-4zm3.515 7.008L14.438 10 8 13.433 1.562 10 4.25 8.567l3.515 1.874a.5.5 0 0 0 .47 0l3.515-1.874zM8 9.433 1.562 6 8 2.567 14.438 6 8 9.433z\" />\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"ms-3 lh-1\">\r\n");
      out.write("                                            <h6 class=\"mb-1\">\r\n");
      out.write("                                                Changelog <span class=\"text-primary ms-1\">v1.2.0</span>\r\n");
      out.write("                                            </h6>\r\n");
      out.write("                                            <p class=\"mb-0 small\">See what's new</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
