/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-10-01 12:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/User/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1692261710617L));
    _jspx_dependants.put("jar:file:/C:/Users/User/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/User/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244306776L));
    _jspx_dependants.put("jar:file:/C:/Users/User/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta content=\"Codescandy\" name=\"author\">\r\n");
      out.write("    <title>FreshCart </title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/dropzone/dist/min/dropzone.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/slick-carousel/slick/slick.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/slick-carousel/slick/slick-theme.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/tiny-slider/dist/tiny-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon icon-->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/favicon/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Libs CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/bootstrap-icons/font/bootstrap-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/feather-webfont/dist/feather-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/simplebar/dist/simplebar.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/theme.min.css\">\r\n");
      out.write("    <!-- Google tag (gtag.js) -->\r\n");
      out.write("    <script async src=\"https://www.googletagmanager.com/gtag/js?id=G-M8S4MT3EYG\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        window.dataLayer = window.dataLayer || [];\r\n");
      out.write("        function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("        gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("        gtag('config', 'G-M8S4MT3EYG');\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"userModal\" tabindex=\"-1\" aria-labelledby=\"userModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content p-4\">\r\n");
      out.write("            <div class=\"modal-header border-0\">\r\n");
      out.write("                <h5 class=\"modal-title fs-3 fw-bold\" id=\"userModalLabel\">Sign Up</h5>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"fullName\" class=\"form-label\">Name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"fullName\" placeholder=\"Enter Your Name\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"email\" class=\"form-label\">Email address</label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Enter Email address\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mb-5\">\r\n");
      out.write("                        <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Enter Password\" required=\"\">\r\n");
      out.write("                        <small class=\"form-text\">By Signup, you agree to our <a href=\"#!\">Terms of Service</a> & <a\r\n");
      out.write("                                href=\"#!\">Privacy Policy</a></small>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Sign Up</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer border-0 justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("                Already have an account? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("signin\">Sign in</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Shop Cart -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasRight\" aria-labelledby=\"offcanvasRightLabel\">\r\n");
      out.write("    <div class=\"offcanvas-header border-bottom\">\r\n");
      out.write("        <div class=\"text-start\">\r\n");
      out.write("            <h5 id=\"offcanvasRightLabel\" class=\"mb-0 fs-4\">Shop Cart</h5>\r\n");
      out.write("            <small>Location in 382480</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close text-reset\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"offcanvas-body\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("            <!-- alert -->\r\n");
      out.write("            <div class=\"alert alert-danger p-2\" role=\"alert\">\r\n");
      out.write("                You have got FREE delivery. Start <a href=\"#!\" class=\"alert-link\">checkout now!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"list-group list-group-flush\">\r\n");
      out.write("                <!-- list group -->\r\n");
      out.write("                <li class=\"list-group-item py-3 ps-0 border-top\">\r\n");
      out.write("                    <!-- row -->\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-6 col-md-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/products/product-img-1.jpg\" alt=\"Ecommerce\"\r\n");
      out.write("                                     class=\"icon-shape icon-xxl\">\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <!-- title -->\r\n");
      out.write("                                    <a href=\"pages/shop-single.html\" class=\"text-inherit\">\r\n");
      out.write("                                        <h6 class=\"mb-0\">Haldiram's Sev Bhujia</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <span><small class=\"text-muted\">.98 / lb</small></span>\r\n");
      out.write("                                    <!-- text -->\r\n");
      out.write("                                    <div class=\"mt-2 small lh-1\"> <a href=\"#!\" class=\"text-decoration-none text-inherit\"> <span\r\n");
      out.write("                                            class=\"me-1 align-text-bottom\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                         stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                         class=\"feather feather-trash-2 text-success\">\r\n");
      out.write("                      <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                      <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\">\r\n");
      out.write("                      </path>\r\n");
      out.write("                      <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\"></line>\r\n");
      out.write("                      <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\"></line>\r\n");
      out.write("                    </svg></span><span class=\"text-muted\">Remove</span></a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- input group -->\r\n");
      out.write("                        <div class=\"col-4 col-md-3 col-lg-3\">\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <div class=\"input-group input-spinner  \">\r\n");
      out.write("                                <input type=\"button\" value=\"-\" class=\"button-minus  btn  btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                                <input type=\"number\" step=\"1\" max=\"10\" value=\"1\" name=\"quantity\"\r\n");
      out.write("                                       class=\"quantity-field form-control-sm form-input   \">\r\n");
      out.write("                                <input type=\"button\" value=\"+\" class=\"button-plus btn btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- price -->\r\n");
      out.write("                        <div class=\"col-2 text-lg-end text-start text-md-end col-md-2\">\r\n");
      out.write("                            <span class=\"fw-bold\">$5.00</span>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- list group -->\r\n");
      out.write("                <li class=\"list-group-item py-3 ps-0\">\r\n");
      out.write("                    <!-- row -->\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-6 col-md-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/products/product-img-2.jpg\" alt=\"Ecommerce\"\r\n");
      out.write("                                     class=\"icon-shape icon-xxl\">\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <a href=\"pages/shop-single.html\" class=\"text-inherit\">\r\n");
      out.write("                                        <h6 class=\"mb-0\">NutriChoice Digestive </h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <span><small class=\"text-muted\">250g</small></span>\r\n");
      out.write("                                    <!-- text -->\r\n");
      out.write("                                    <div class=\"mt-2 small lh-1\"> <a href=\"#!\" class=\"text-decoration-none text-inherit\"> <span\r\n");
      out.write("                                            class=\"me-1 align-text-bottom\">\r\n");
      out.write("                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                             stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                             class=\"feather feather-trash-2 text-success\">\r\n");
      out.write("                          <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                          <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\">\r\n");
      out.write("                          </path>\r\n");
      out.write("                          <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\"></line>\r\n");
      out.write("                          <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\"></line>\r\n");
      out.write("                        </svg></span><span class=\"text-muted\">Remove</span></a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- input group -->\r\n");
      out.write("                        <div class=\"col-4 col-md-3 col-lg-3\">\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <div class=\"input-group input-spinner  \">\r\n");
      out.write("                                <input type=\"button\" value=\"-\" class=\"button-minus  btn  btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                                <input type=\"number\" step=\"1\" max=\"10\" value=\"1\" name=\"quantity\"\r\n");
      out.write("                                       class=\"quantity-field form-control-sm form-input   \">\r\n");
      out.write("                                <input type=\"button\" value=\"+\" class=\"button-plus btn btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- price -->\r\n");
      out.write("                        <div class=\"col-2 text-lg-end text-start text-md-end col-md-2\">\r\n");
      out.write("                            <span class=\"fw-bold text-danger\">$20.00</span>\r\n");
      out.write("                            <div class=\"text-decoration-line-through text-muted small\">$26.00</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- list group -->\r\n");
      out.write("                <li class=\"list-group-item py-3 ps-0\">\r\n");
      out.write("                    <!-- row -->\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-6 col-md-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/products/product-img-3.jpg\" alt=\"Ecommerce\"\r\n");
      out.write("                                     class=\"icon-shape icon-xxl\">\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <!-- title -->\r\n");
      out.write("                                    <a href=\"pages/shop-single.html\" class=\"text-inherit\">\r\n");
      out.write("                                        <h6 class=\"mb-0\">Cadbury 5 Star Chocolate</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <span><small class=\"text-muted\">1 kg</small></span>\r\n");
      out.write("                                    <!-- text -->\r\n");
      out.write("                                    <div class=\"mt-2 small lh-1\"> <a href=\"#!\" class=\"text-decoration-none text-inherit\"> <span\r\n");
      out.write("                                            class=\"me-1 align-text-bottom\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                         stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                         class=\"feather feather-trash-2 text-success\">\r\n");
      out.write("                      <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                      <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\">\r\n");
      out.write("                      </path>\r\n");
      out.write("                      <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\"></line>\r\n");
      out.write("                      <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\"></line>\r\n");
      out.write("                    </svg></span><span class=\"text-muted\">Remove</span></a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- input group -->\r\n");
      out.write("                        <div class=\"col-4 col-md-3 col-lg-3\">\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <div class=\"input-group input-spinner  \">\r\n");
      out.write("                                <input type=\"button\" value=\"-\" class=\"button-minus  btn  btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                                <input type=\"number\" step=\"1\" max=\"10\" value=\"1\" name=\"quantity\"\r\n");
      out.write("                                       class=\"quantity-field form-control-sm form-input   \">\r\n");
      out.write("                                <input type=\"button\" value=\"+\" class=\"button-plus btn btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- price -->\r\n");
      out.write("                        <div class=\"col-2 text-lg-end text-start text-md-end col-md-2\">\r\n");
      out.write("                            <span class=\"fw-bold\">$15.00</span>\r\n");
      out.write("                            <div class=\"text-decoration-line-through text-muted small\">$20.00</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- list group -->\r\n");
      out.write("                <li class=\"list-group-item py-3 ps-0\">\r\n");
      out.write("                    <!-- row -->\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-6 col-md-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/products/product-img-4.jpg\" alt=\"Ecommerce\"\r\n");
      out.write("                                     class=\"icon-shape icon-xxl\">\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <!-- title -->\r\n");
      out.write("                                    <!-- title -->\r\n");
      out.write("                                    <a href=\"pages/shop-single.html\" class=\"text-inherit\">\r\n");
      out.write("                                        <h6 class=\"mb-0\">Onion Flavour Potato</h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <span><small class=\"text-muted\">250g</small></span>\r\n");
      out.write("                                    <!-- text -->\r\n");
      out.write("                                    <div class=\"mt-2 small lh-1\"> <a href=\"#!\" class=\"text-decoration-none text-inherit\"> <span\r\n");
      out.write("                                            class=\"me-1 align-text-bottom\">\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                                     stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                                     class=\"feather feather-trash-2 text-success\">\r\n");
      out.write("                                  <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                                  <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\">\r\n");
      out.write("                                  </path>\r\n");
      out.write("                                  <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\"></line>\r\n");
      out.write("                                  <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\"></line>\r\n");
      out.write("                                </svg></span><span class=\"text-muted\">Remove</span></a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- input group -->\r\n");
      out.write("                        <div class=\"col-4 col-md-3 col-lg-3\">\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <div class=\"input-group input-spinner  \">\r\n");
      out.write("                                <input type=\"button\" value=\"-\" class=\"button-minus  btn  btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                                <input type=\"number\" step=\"1\" max=\"10\" value=\"1\" name=\"quantity\"\r\n");
      out.write("                                       class=\"quantity-field form-control-sm form-input   \">\r\n");
      out.write("                                <input type=\"button\" value=\"+\" class=\"button-plus btn btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- price -->\r\n");
      out.write("                        <div class=\"col-2 text-lg-end text-start text-md-end col-md-2\">\r\n");
      out.write("                            <span class=\"fw-bold\">$15.00</span>\r\n");
      out.write("                            <div class=\"text-decoration-line-through text-muted small\">$20.00</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- list group -->\r\n");
      out.write("                <li class=\"list-group-item py-3 ps-0 border-bottom\">\r\n");
      out.write("                    <!-- row -->\r\n");
      out.write("                    <div class=\"row align-items-center\">\r\n");
      out.write("                        <div class=\"col-6 col-md-6 col-lg-7\">\r\n");
      out.write("                            <div class=\"d-flex\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/images/products/product-img-5.jpg\" alt=\"Ecommerce\"\r\n");
      out.write("                                     class=\"icon-shape icon-xxl\">\r\n");
      out.write("                                <div class=\"ms-3\">\r\n");
      out.write("                                    <!-- title -->\r\n");
      out.write("                                    <a href=\"pages/shop-single.html\" class=\"text-inherit\">\r\n");
      out.write("                                        <h6 class=\"mb-0\">Salted Instant Popcorn </h6>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <span><small class=\"text-muted\">100g</small></span>\r\n");
      out.write("                                    <!-- text -->\r\n");
      out.write("                                    <div class=\"mt-2 small lh-1\"> <a href=\"#!\" class=\"text-decoration-none text-inherit\"> <span\r\n");
      out.write("                                            class=\"me-1 align-text-bottom\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\" viewBox=\"0 0 24 24\" fill=\"none\"\r\n");
      out.write("                         stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("                         class=\"feather feather-trash-2 text-success\">\r\n");
      out.write("                      <polyline points=\"3 6 5 6 21 6\"></polyline>\r\n");
      out.write("                      <path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\">\r\n");
      out.write("                      </path>\r\n");
      out.write("                      <line x1=\"10\" y1=\"11\" x2=\"10\" y2=\"17\"></line>\r\n");
      out.write("                      <line x1=\"14\" y1=\"11\" x2=\"14\" y2=\"17\"></line>\r\n");
      out.write("                    </svg></span><span class=\"text-muted\">Remove</span></a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- input group -->\r\n");
      out.write("                        <div class=\"col-4 col-md-3 col-lg-3\">\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <!-- input -->\r\n");
      out.write("                            <div class=\"input-group input-spinner  \">\r\n");
      out.write("                                <input type=\"button\" value=\"-\" class=\"button-minus  btn  btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                                <input type=\"number\" step=\"1\" max=\"10\" value=\"1\" name=\"quantity\"\r\n");
      out.write("                                       class=\"quantity-field form-control-sm form-input   \">\r\n");
      out.write("                                <input type=\"button\" value=\"+\" class=\"button-plus btn btn-sm \" data-field=\"quantity\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- price -->\r\n");
      out.write("                        <div class=\"col-2 text-lg-end text-start text-md-end col-md-2\">\r\n");
      out.write("                            <span class=\"fw-bold\">$15.00</span>\r\n");
      out.write("                            <div class=\"text-decoration-line-through text-muted small\">$25.00</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- btn -->\r\n");
      out.write("            <div class=\"d-flex justify-content-between mt-4\">\r\n");
      out.write("                <a href=\"#!\" class=\"btn btn-primary\">Continue Shopping</a>\r\n");
      out.write("                <a href=\"#!\" class=\"btn btn-dark\">Update Cart</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"locationModal\" tabindex=\"-1\" aria-labelledby=\"locationModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-sm modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-body p-6\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-start \">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h5 class=\"mb-1\" id=\"locationModalLabel\">Choose your Delivery Location</h5>\r\n");
      out.write("                        <p class=\"mb-0 small\">Enter your address and we will specify the offer you area. </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"my-5\">\r\n");
      out.write("                    <input type=\"search\" class=\"form-control\" placeholder=\"Search your area\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-2\">\r\n");
      out.write("                    <h6 class=\"mb-0\">Select Location</h6>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-outline-gray-400 text-muted btn-sm\">Clear All</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div data-simplebar style=\"height:300px;\">\r\n");
      out.write("                        <div class=\"list-group list-group-flush\">\r\n");
      out.write("\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action active\">\r\n");
      out.write("                                <span>Alabama</span><span>Min:$20</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Alaska</span><span>Min:$30</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Arizona</span><span>Min:$50</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>California</span><span>Min:$29</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Colorado</span><span>Min:$80</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Florida</span><span>Min:$90</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Arizona</span><span>Min:$50</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>California</span><span>Min:$29</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Colorado</span><span>Min:$80</span></a>\r\n");
      out.write("                            <a href=\"#\"\r\n");
      out.write("                               class=\"list-group-item d-flex justify-content-between align-items-center px-2 py-3 list-group-item-action\">\r\n");
      out.write("                                <span>Florida</span><span>Min:$90</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Javascript-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/rater-js/index.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/dropzone/dist/min/dropzone.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/request-interceptor.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- Libs JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/simplebar/dist/simplebar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Theme JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/theme.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/jquery-countdown/dist/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendors/countdown.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/slick-carousel/slick/slick.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendors/slick-slider.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/libs/tiny-slider/dist/min/tiny-slider.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendors/tns-slider.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendors/zoom.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/vendors/increment-value.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fblock_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(429,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("content");
      _jspx_th_layout_005fblock_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fblock_005f0, null));
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fblock_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f1 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f1);
    try {
      _jspx_th_layout_005fblock_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(459,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f1.setName("script");
      _jspx_th_layout_005fblock_005f1.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fblock_005f1, null));
      _jspx_th_layout_005fblock_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
